"""
Streamlit Web Interface for the HomeFinder multi-agent system.

This module provides a user-friendly dashboard for real estate analysis,
allowing users to input property URLs, financial parameters, and view
comprehensive evaluation reports generated by the LangGraph backend.
"""

import asyncio
from typing import Any, Dict, cast

import markdown
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from src.agents.nodes import (
    commuter_node,
    data_extractor_node,
    evaluator_node,
    financial_node,
    negotiator_node,
    osint_node,
)
from src.core.config import (
    CLAUDE_HAIKU,
    CLAUDE_SONNET,
    GEMINI_FLASH,
    GEMINI_FLASH_LITE,
    GPT_4O,
    GPT_4O_MINI,
    KIMI_V1_8K,
    KIMI_V1_32K,
)
from src.core.graph import app as graph_app
from src.core.logging_config import setup_logging
from src.core.state import PropertyState

# Initialize Logging
setup_logging()

# ─────────────────────────────────────────────────────────────────────────────
# 1. PAGE CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(page_title="Home Finder", page_icon="🏢", layout="wide")

# ─────────────────────────────────────────────────────────────────────────────
# 2. CUSTOM CSS - PREMIUM PROPTECH THEME
# ─────────────────────────────────────────────────────────────────────────────
with open("assets/style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# 3. UI - HEADER
# ─────────────────────────────────────────────────────────────────────────────
st.markdown(
    """
<div class="premium-header">
    <h1>Home Finder<span style="color: #0F52BA;">.</span></h1>
    <p>Advanced AI-driven real estate investment evaluation</p>
</div>
""",
    unsafe_allow_html=True,
)

# ─────────────────────────────────────────────────────────────────────────────
# 4. UI - INPUT FORM
# ─────────────────────────────────────────────────────────────────────────────
st.markdown('<div class="section-title">📍 Property Details</div>', unsafe_allow_html=True)

col_url, col_addr = st.columns([2, 1], gap="medium")
with col_url:
    target_url = st.text_input(
        "Real Estate Listing URL", placeholder="https://www.immobiliare.it/annunci/..."
    )
with col_addr:
    user_office_address = st.text_input("Office Address", value="Piazza del Duomo, Milan")

with st.expander("🛠️ Manual Text Entry (Use if scraper is blocked)"):
    manual_text = st.text_area("Paste the listing text here", height=150)

st.markdown('<div class="section-title">🏛️ Parameters & Settings</div>', unsafe_allow_html=True)

f_col1, f_col2, f_col3, f_col4, f_col5 = st.columns(5)
with f_col1:
    max_budget = st.number_input("Max Budget (€)", min_value=10000, value=350000, step=10000)
with f_col2:
    down_payment = st.number_input("Down Payment (€)", value=50000, step=5000)
with f_col3:
    interest_rate = st.number_input("Interest Rate (%)", value=3.5, step=0.1, format="%.1f")
with f_col4:
    loan_term_years = st.number_input("Term (Years)", value=30, min_value=1, max_value=40)
with f_col5:
    negotiation_language = st.selectbox("Negotiation Language", ["English", "Italian", "Spanish", "French", "German"])

st.markdown('<div class="section-title">🤖 AI Configuration</div>', unsafe_allow_html=True)
ai_col1, ai_col2 = st.columns(2)
with ai_col1:
    provider = st.selectbox(
        "AI Provider",
        ["Google Gemini", "Anthropic Claude", "OpenAI GPT", "Moonshot Kimi"],
        help="Select the AI provider to use for the analysis."
    )

# Map provider to specific lite/pro models
if provider == "Google Gemini":
    lite_model = GEMINI_FLASH_LITE
    pro_model = GEMINI_FLASH
elif provider == "Anthropic Claude":
    lite_model = CLAUDE_HAIKU
    pro_model = CLAUDE_SONNET
elif provider == "OpenAI GPT":
    lite_model = GPT_4O_MINI
    pro_model = GPT_4O
else:  # Moonshot Kimi
    lite_model = KIMI_V1_8K
    pro_model = KIMI_V1_32K

with ai_col2:
    st.info(f"Using **{lite_model}** for extraction and **{pro_model}** for evaluation.")

# ─────────────────────────────────────────────────────────────────────────────
# 5. ACTION BUTTON
# ─────────────────────────────────────────────────────────────────────────────
st.write("")
_, col_btn, _ = st.columns([1, 2, 1])
with col_btn:
    start_analysis = st.button("🚀 Analyze Property", type="primary", use_container_width=True)
st.write("")


# ─────────────────────────────────────────────────────────────────────────────
# 6. EXECUTION LOGIC
# ─────────────────────────────────────────────────────────────────────────────
async def run_langgraph_stream(initial_state: Dict[str, Any]) -> Dict[str, Any]:
    """Runs the LangGraph orchestration and streams updates to the UI.

    Args:
        initial_state: Dictionary containing initial user inputs.

    Returns:
        Dict[str, Any]: The final state of the graph after completion.
    """
    final_state = initial_state.copy()
    async for output in graph_app.astream(cast(Any, initial_state)):
        for node_name, node_state in output.items():
            if node_name == "scraper_node":
                st.write("✅ **Scraper:** Content extracted.")
            elif node_name == "data_extractor_node":
                st.write("🧠 **AI Extractor:** Data structured.")
            elif node_name == "commuter_node":
                st.write("🚗 **Maps:** Commute calculated.")
            elif node_name == "osint_node":
                st.write("🌍 **OSINT:** Neighborhood analyzed.")
            elif node_name == "financial_node":
                st.write("💰 **Financial:** Mortgage simulated.")
            elif node_name == "evaluator_node":
                st.write("✍️ **Evaluator:** Report drafted.")
            elif node_name == "negotiator_node":
                st.write("🤝 **Negotiator:** Email generated.")

            # Robust update: only update if node_state is a dictionary
            if isinstance(node_state, dict):
                final_state.update(node_state)
    return final_state


if start_analysis:
    if not target_url and not manual_text:
        st.warning("Please provide a URL or manual text.")
    else:
        with st.status("Initializing Analysis Engine...", expanded=True) as status:
            initial_state: Dict[str, Any] = {
                "user_office_address": user_office_address,
                "max_budget": float(max_budget),
                "down_payment": float(down_payment),
                "interest_rate": interest_rate / 100.0,
                "loan_term_years": int(loan_term_years),
                "negotiation_language": negotiation_language,
                "lite_model": lite_model,
                "pro_model": pro_model,
            }

            if manual_text:
                st.write("📝 Using manual text input...")
                state = initial_state.copy()
                state["raw_listing_text"] = manual_text

                # Manual sequential execution for manual text
                update = asyncio.run(data_extractor_node(cast(PropertyState, state)))
                if isinstance(update, dict):
                    state.update(update)
                st.write("🧠 **AI Extractor:** Data structured.")

                if state.get("hard_constraints_met"):
                    # Run subsequent nodes
                    update = asyncio.run(commuter_node(cast(PropertyState, state)))
                    if isinstance(update, dict):
                        state.update(update)
                    st.write("🚗 **Maps:** Commute calculated.")

                    update = asyncio.run(osint_node(cast(PropertyState, state)))
                    if isinstance(update, dict):
                        state.update(update)
                    st.write("🌍 **OSINT:** Neighborhood analyzed.")

                    update = asyncio.run(financial_node(cast(PropertyState, state)))
                    if isinstance(update, dict):
                        state.update(update)
                    st.write("💰 **Financial:** Mortgage simulated.")

                    st.write("⚙️ **Engine:** Parallel calculations completed.")

                    update = asyncio.run(evaluator_node(cast(PropertyState, state)))
                    if isinstance(update, dict):
                        state.update(update)
                    st.write("✍️ **Evaluator:** Report drafted.")

                    update = asyncio.run(negotiator_node(cast(PropertyState, state)))
                    if isinstance(update, dict):
                        state.update(update)
                    st.write("🤝 **Negotiator:** Email generated.")

                final_output = state
            else:
                initial_state["target_url"] = target_url
                final_output = asyncio.run(run_langgraph_stream(initial_state))

            status.update(label="Analysis Complete!", state="complete", expanded=False)

        # ─────────────────────────────────────────────────────────────────────────────
        # 7. RESULTS DISPLAY
        # ─────────────────────────────────────────────────────────────────────────────
        st.markdown('<div class="section-title">📊 Analysis Results</div>', unsafe_allow_html=True)

        params = final_output.get("extracted_parameters")

        if params is None:
            st.error(
                final_output.get(
                    "evaluation_report", "❌ Analysis failed. The listing might be inaccessible."
                )
            )
        elif not final_output.get("hard_constraints_met"):
            price = getattr(params, "price", 0)
            st.warning(f"⚠️ Property exceeds budget. Price: € {price:,.0f}".replace(",", "."))
        else:
            # Metrics Row (Top Level)
            score = final_output.get("final_score", 0)
            price = getattr(params, "price", 0)
            commute = cast(Any, final_output.get("commute_data"))
            time = f"{getattr(commute, 'transit_time_mins', 'N/A')} min" if commute else "N/A"
            osint = cast(Any, final_output.get("osint_data"))

            st.markdown(
                f"""
            <div class="metric-container">
                <div class="metric-card">
                    <div class="metric-label">Investment Score</div>
                    <div class="metric-value" style="color: #38BDF8;">{score}/100</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Asking Price</div>
                    <div class="metric-value" style="color: #F8FAFC;">€ {price:,.0f}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Commute</div>
                    <div class="metric-value" style="color: #F8FAFC;">{time}</div>
                </div>
            </div>
            """,
                unsafe_allow_html=True,
            )

            # --- TABS ---
            tab_summary, tab_fin, tab_neigh, tab_neg = st.tabs(
                ["📋 Summary", "💰 Financials", "🏙️ Neighborhood", "✉️ Negotiation"]
            )

            with tab_summary:
                col_rep, col_spec = st.columns([2, 1])
                with col_rep:
                    report_md = final_output.get("evaluation_report", "")
                    if any(emoji in report_md for emoji in ["⚠️", "🔑", "🕒", "❌"]):
                        st.error(report_md)
                    else:
                        st.markdown("### Executive Summary")
                        # Convert markdown to HTML before injecting into the styled div
                        report_html = markdown.markdown(report_md, extensions=['extra', 'nl2br'])
                        st.markdown(f'<div class="report-box">{report_html}</div>', unsafe_allow_html=True)

                with col_spec:
                    st.markdown("### Property Specs")
                    spec_items = {
                        "Address": getattr(params, "property_address", "N/A"),
                        "Price/sqm": f"€ {getattr(params, 'price_per_sqm', 0):,.0f}" if getattr(params, 'price_per_sqm', None) else "N/A",
                        "Surface": f"{getattr(params, 'sqm', 'N/A')} sqm",
                        "Bedrooms": getattr(params, "bedrooms", "N/A"),
                        "Bathrooms": getattr(params, "bathrooms", "N/A"),
                        "Floor": getattr(params, "floor", "N/A"),
                        "Energy Class": getattr(params, "energy_class", "N/A"),
                        "Elevator": "✅ Yes" if getattr(params, "has_elevator", None) else "❌ No",
                        "Barrier Free": "✅ Yes" if not getattr(params, "has_architectural_barriers", True) else "❌ No",
                    }
                    for label, value in spec_items.items():
                        st.markdown(f"**{label}:** {value}")

            with tab_fin:
                st.markdown("### Financial Projection")
                fin = cast(Any, final_output.get("financial_data", {}))
                if fin:
                    c1, c2 = st.columns([1, 1])
                    with c1:
                        # Pie Chart for Loan vs Down Payment
                        loan_amt = price - float(down_payment)
                        fig = go.Figure(data=[go.Pie(
                            labels=['Down Payment', 'Loan Amount'],
                            values=[float(down_payment), loan_amt],
                            hole=.4,
                            marker_colors=['#0F52BA', '#E2E8F0']
                        )])
                        fig.update_layout(
                            showlegend=True,
                            margin={"t": 0, "b": 0, "l": 0, "r": 0},
                            height=300,
                            paper_bgcolor='rgba(0,0,0,0)',
                            plot_bgcolor='rgba(0,0,0,0)',
                            font={"color": "#F8FAFC"}
                        )
                        st.plotly_chart(fig, use_container_width=True)

                    with c2:
                        st.info(f"**Original Installment**\n\n€ {fin.get('original_installment', 0):,.2f}")
                        st.success(f"**Target Installment (-{fin.get('discount_percentage', 0)}%)**\n\n€ {fin.get('discounted_installment', 0):,.2f}")
                        st.metric("Savings / Month", f"€ {fin.get('original_installment', 0) - fin.get('discounted_installment', 0):,.2f}")

            with tab_neigh:
                st.markdown("### Neighborhood Insights")
                if osint:
                    col_chart, col_data = st.columns([1, 1])
                    with col_chart:
                        # Radar Chart for Scores
                        df = pd.DataFrame({
                            "r": [
                                (getattr(osint, 'safety_score', 0) + 1) * 50,
                                getattr(osint, 'amenities_score', 0) * 100,
                                getattr(osint, 'public_transport_score', 0) * 100,
                                (getattr(osint, 'noise_level', 0) + 1) * 50
                            ],
                            "theta": ['Safety', 'Amenities', 'Transport', 'Quietness']
                        })
                        fig = px.line_polar(df, r='r', theta='theta', line_close=True)
                        fig.update_traces(fill='toself', line_color='#38BDF8')
                        fig.update_layout(
                            polar={
                                "radialaxis": {"visible": True, "range": [0, 100], "gridcolor": "#334155", "labelalias": {}},
                                "angularaxis": {"gridcolor": "#334155", "linecolor": "#334155"}
                            },
                            showlegend=False,
                            margin={"t": 40, "b": 40, "l": 40, "r": 40},
                            height=300,
                            paper_bgcolor='rgba(0,0,0,0)',
                            plot_bgcolor='rgba(0,0,0,0)',
                            font={"color": "#F8FAFC"}
                        )
                        st.plotly_chart(fig, use_container_width=True)

                    with col_data:
                        st.markdown(f"**Connectivity:** {getattr(osint, 'broadband_type', 'N/A')}")
                        st.markdown(f"**Points of Interest:** {getattr(osint, 'poi_count', 'N/A')} nearby")
                        st.markdown(f"**Commute Distance:** {getattr(commute, 'distance_km', 'N/A')} km")
                else:
                    st.write("No neighborhood data available.")

            with tab_neg:
                email_md = final_output.get("negotiation_email", "")
                if any(emoji in email_md for emoji in ["⚠️", "🔑", "🕒", "❌"]):
                    st.error(email_md)
                else:
                    st.markdown("### Negotiation Strategy")
                    # Convert markdown to HTML before injecting into the styled div
                    email_html = markdown.markdown(email_md, extensions=['extra', 'nl2br'])
                    st.markdown(f'<div class="report-box">{email_html}</div>', unsafe_allow_html=True)
