services:
  homefinder:
    build: .
    container_name: homefinder-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./assets:/app/assets
      - ./.streamlit:/app/.streamlit
      - ./app.py:/app/app.py
    restart: unless-stopped

networks:
  default:
    name: homefinder-network
